[build]
builder = "nixpacks"
buildCommand = "composer install --ignore-platform-reqs --no-dev --optimize-autoloader"

[deploy]
preDeployCommand = ["php artisan migrate"]
startCommand = "php artisan serve --host=0.0.0.0 --port=8000"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
